apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: 1.15.5

    helm:
      values: |
        kubeProxyReplacement: strict

        routingMode: native

        ipv4NativeRoutingCIDR: "10.0.0.0/16"

        enableIPv4Masquerade: true

        # k8sServiceHost: ${KUBERNETES_SERVICE_HOST}
        # k8sServicePort: ${KUBERNETES_SERVICE_PORT}

        ipam:
          mode: kubernetes

        # eni:
        #   enabled: true

        # hubble:
        #   enabled: true
        #   relay:
        #     enabled: true
        #   ui:
        #     enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
     prune: true
     selfHeal: true
